name: Final signoff

on:
  issues:
    types: [labeled]

  workflow_dispatch:
        
jobs:
  find-action-name:
    uses: rajbos/github-actions-requests/.github/workflows/get-action-from-issue.yml@add-final-clone
    with:
      issue_number: 11

  tag-a-user:
    runs-on: ubuntu-latest
    steps:     
      - run: echo "Hello world"

      