name: Final signoff

on:
  issues:
    types: [labeled]

  workflow_dispatch: 
    inputs:
      issue:
        description: 'Issue number to work with'
        required: true
        default: '11'
        
jobs:
  find-action-name:
    uses: rajbos/github-actions-requests/.github/workflows/get-action-from-issue.yml@add-final-clone
    with:
      issue_number: 11

  test-parameters:
    runs-on: ubuntu-latest
    needs: find-action-name
    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v5  
      name: Check input variables have values     
      with: 
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          
          // note: owner is now the organization the FORK lives in:
          const repo = `${{ needs.find-action-name.outputs.name }}`
          const owner = `${{ needs.find-action-name.outputs.owner }}`
          const issue_number = `${{ needs.find-action-name.outputs.request_issue }}`

          console.log(`owner: ${owner}, repo: ${repo}, with issue_number: ${issue_number}`)

      