name: Liguist test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/linguist-test.yml"

jobs:
  get-languages:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.analysis.outputs.languages }}
    steps:
      - uses: ruby/setup-ruby@v1
        name: Setup Ruby
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - run : gem install github-linguist
        name: Install linguist gem

      - run: git clone https://github.com/rajbos/github-actions-requests.git
        name: Clone actions repo

      - name: Get linguist analysis
        id: analysis
        run: | 
         cd github-actions-requests
         linguist=$(github-linguist --json)
         echo "Linquist results:"
         echo $linguist
         echo "::set-output name=languages::$linguist"

  get-analysis-results:
    runs-on: ubuntu-latest
    needs: get-languages
    steps:
      # load results from analysis job
      - run: echo "${{ needs.get-language.outputs.languages }}"